### PR TITLE
Fix issue #34: delete PostgreSQL database before restoration

### PR DESCRIPTION
**Pull request by harobed**

### CODE REVIEW

**Comment by cimnine** [comment]
Instead of dropping the database explicitly, what about adding the "-c" option to `pg_dump`?

From the [pg_dump documentation][pg_dump_man]:

> `-c`
> `--clean`
> Output commands to clean (drop) database objects prior to (the commands for) creating them.
> This option is only meaningful for the plain-text format. For the archive formats, you can specify the option when you call pg_restore.

[pg_dump_man]: https://www.postgresql.org/docs/9.3/static/app-pgdump.html

**Comment by harobed** [comment]
> Instead of dropping the database explicitly, what about adding the "-c" option to pg_dump?

I tried that first but it don't working for me.

@cimnine can you test it?

**Comment by cimnine** [comment]
```bash
docker-compose exec postgres sh -c 'pg_dump -cU $POSTGRES_USER $POSTGRES_DB' | gzip > db_dump.sql.gz
gunzip -c db_dump.sql.gz | docker exec -i $(docker-compose ps -q postgres) sh -c 'psql -U $POSTGRES_USER $POSTGRES_DB'
```

It works for me like this. The '-c' option has to be supplied to `pg_dump` and not to `psql`, did you do this?

**Comment by harobed** [comment]
> It works for me like this. 

It's work also for me.

Can you update the readme + close this pull request?

Best regards,
Stéphane

**Comment by cimnine** [comment]
Once again, thank you for your feedback!

**Pull request closed without merging**
