### PR TITLE
Adding in support for NAPALM

### PR DESCRIPTION
**Pull request by bdlamprecht**
As discussed in a direct-message conversation via the NetworkToCode Slack channel today, this PR adds in basic support for `NAPALM` to the `base` image of `ninech/netbox-docker`.

I've tested this in my environment (after adding the appropriate values for `NAPALM_USERNAME` and `NAPALM_PASSWORD`). If someone leaves these values blank, I can not see any difference in the performance of this container.

I also found that the existing value of `5` for `NAPALM_TIMEOUT` was not sufficient for my fairly latency-free environment so I changed it to be `10` instead.

If a user needs more advanced configurations for NAPALM (such as `NAPALM_ARGS`), due to the fact that Docker can't pass `dict` objects as `ENV` variables, the best I could come up with is the following in `netbox.env`:
```
NAPALM_USERNAME=netbox
NAPALM_PASSWORD=my_cisco_password
NAPALM_ARGS1_KEY=secret
NAPALM_ARGS1_VALUE=my_cisco_enable_password
NAPALM_TIMEOUT=10
```
With the following changes to `configuration/configuration.py`:
```
# NAPALM optional arguments (see http://napalm.readthedocs.io/en/latest/support/#optional-arguments). Arguments must
# be provided as a dictionary.
NAPALM_ARGS = {
  os.environ.get('NAPALM_ARGS1_KEY', ''):os.environ.get('NAPALM_ARGS1_VALUE', ''),
}
```

However, I **didn't** add that to this PR as _most_ scenarios will not need to include those parameters (if their devices use the defaults).

### CODE REVIEW

**Comment by cimnine** [comment]
Thanks for your PR. I will look at it in more detail later. Some early thoughts: It would be nice to have something in the README regarding the setup / configuration of Napalm using this image, which at least includes a link to the appropriate Netbox documentation on the topic.

**Comment by bdlamprecht** [comment]
Okay, adding links to the documentation makes sense.

Do you think something as simple as adding a section to the `README.md` with a link to the [appropriate section](http://netbox.readthedocs.io/en/latest/configuration/optional-settings/#napalm_username) would work?

**Comment by cimnine** [comment]
> Do you think something as simple as adding a section to the README.md with a link to the appropriate section would work?

Yes, and maybe a sentence or two about which ENV variables to define.

**Comment by bdlamprecht** [comment]
I wasn't quite sure where in the `README.md` I should add the information, so I took a best guess.  Feel free to move it to another location if you think it would fit better elsewhere.

**Comment by cimnine** [comment]
Thanks for your contribution. The PR was merged in ac41f7ed78664259ca3b6cdf067410cbc61ee1c2, although Github did not seem to realize this. (Probably because I had to rebase it.)

**Comment by bdlamprecht** [comment]
Great.  Obviously I had to rebuild the images locally since a new version of NetBox hasn't been released yet.  Once I built images for both `v2.3.1` and `v2.3.1-ldap` , `NAPALM` worked great in my environment.

**Comment by cimnine** [comment]
I manually deleted the `v2.3.1` tags from Docker Hub and triggered a new build right now.

**Pull request closed without merging**
