### PR TITLE
Added support for docker secrets

### PR DESCRIPTION
**Pull request by tjakobsson**
When using docker secrets, a file in /run/secrets/ is added. For example, SUPERUSER_PASSWORD_FILE=/run/secrets/superuser_password will populate SUPERUSER_PASSWORD environment variable from the contents of that file. The code to support this is now added to docker/docker-entrypoint.sh for all environment variables.

See https://docs.docker.com/engine/swarm/secrets/ and go to: Advanced example: Use secrets with a WordPress service.

### CODE REVIEW

**Comment by tjakobsson** [comment]
This approach is supported in official postgres, mariadb, mysql and more.

And as I think the end user should be the one determine what is a secret, As even a username can be thought of as a secret, I left it supporting that everything can be a secret, even though you might not use it.

Regarding the configuration approach. This does not remove the possibility to do that. For example, you can use docker config and add configuration.py having that read the secrets directly. Again, something I think the end user already have control as it is today.

**Comment by cimnine** [comment]
> This approach is supported in official postgres, mariadb, mysql and more.

But they don't read secrets from files at all, do they?

**Comment by tjakobsson** [comment]
No they don't.

But supporting it gives the power to the end user to choose how they wanna go about it.

**Comment by cimnine** [comment]
@tjakobsson I know that you wanted more, but I hope #28 will still suit your needs once it's merged. 

Otherwise I can only recommend you to create your own `configuration.py` and mount it into your Netbox container using [Docker Swarm's configuration mechanisms](https://docs.docker.com/engine/swarm/configs/).

**Pull request closed without merging**
