### PR TITLE
Changing 'reports' from a volume to a mapped directory

### PR DESCRIPTION
**Pull request by bdlamprecht**
This will allow easier interaction with the report functionality of the 'netbox' container.

I also added a sample report from the [documentation](https://netbox.readthedocs.io/en/stable/additional-features/reports/#writing-reports) as an example.

Please note, as of submitting this PR, the published documentation still needs to be updated for `v2.5` syntax as noted in NetBox issue [#2709](https://github.com/digitalocean/netbox/issues/2709).

I'm open to other suggestions on naming, but having a Docker `volume` seemed somewhat limiting when you're trying to write and update reports dynamically.

### CODE REVIEW

**Comment by cimnine** [comment]
I was just thinking, whether it would be a good idea to "disable" your example report by default. I.e. rename the file to `devices.py.example`. Or maybe `example_report.py.disabled`?

**Comment by bdlamprecht** [comment]
It doesn't hurt anything to leave it enabled, as there are no `devices` to run the report against (by default).

I'm not opposed to your idea of disabling it by changing the filename as you mentioned, however, I think it is nice to have **_something_** there for the end-user to get an idea of the possibilities of what reports can do.

Just by two cents.

**Comment by cimnine** [comment]
I was thinking that leaving it enabled may cause someone to file issues for it if it's not working to this person's expecations, either here or in the netbox repository. Both of which are unfavourable.

Additionally, until now this project delivered pretty much a vanilla Netbox out of the box. I believe it should stay that way.

Could you therefore rename the report to something that is not recognized by Netbox as a report, e.g. `.example`?

**Comment by bdlamprecht** [comment]
Done per your suggestion.

I also think something that mentions this functionality (such as how to enable it) would be appropriate somewhere in the `README.md` file.

**Comment by cimnine** [comment]
> I also think something that mentions this functionality (such as how to enable it) would be appropriate somewhere in the README.md file.

Absolutely.

**Pull request merged**
